use serde::{Deserialize, Serialize};

use crate::client::spinview::{SpinviewCaid, SpinviewUser};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct SpinviewRequest {
    pub id: String,
    pub slot_id: i32,
    pub slot_width: i32,
    pub slot_height: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bid_floor: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bid_floor_cur: Option<String>,
    pub app_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_package: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_store_url: Option<String>,
    pub ip: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    pub user_agent: String,
    pub os_type: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_level: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfa: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfa_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openudid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caids: Option<Vec<SpinviewCaid>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imei_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_id_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mac_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serialno: Option<String>,
    pub screen_orientation: i32,
    pub screen_width: i32,
    pub screen_height: i32,
    pub screen_dpi: i32,
    pub screen_ppi: i32,
    pub screen_density: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_size: Option<String>,
    pub connection_type: i32,
    pub device_type: i32,
    pub carrier: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mccmnc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wifi_mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rom_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_compiling_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_store_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hag: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_machine: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub init_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub startup_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upgrade_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hard_disk: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_freq: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfa_policy: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ista: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<SpinviewUser>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapse_time: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secure: Option<i32>,
}
