use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct SpinviewVideo {
    pub url: String,
    pub duration: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skip: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cover_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub endcard_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub endcard_html: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_icon_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_button_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_button_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_begin_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_first_quartile_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_midpoint_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_third_quartile_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_end_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_mute_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_unmute_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_skip_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_close_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_pause_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_resume_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_replay_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_fullscreen_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_exit_fullscreen_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_up_scroll_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_down_scroll_urls: Option<Vec<String>>,
}
