use serde::{Deserialize, Serialize};

use super::{MobrtbImage, MobrtbVideo};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct MobrtbAd {
    pub width: i32,
    pub height: i32,
    pub ad_id: String,
    pub creative_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub advertiser_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ratings: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub likes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub downloads: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<MobrtbImage>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<MobrtbImage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<MobrtbImage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<MobrtbVideo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_cover: Option<MobrtbImage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub html_snippet: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    pub action: i32,
    pub target_url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_app_bundle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_app_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_app_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_app_size: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_app_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mini_program_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mini_program_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_url: Option<String>,
    pub win_notice_tracker: String,
    pub impression_trackers: Vec<String>,
    pub click_trackers: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_begin_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_ended_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub install_begin_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub install_ended_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_play_begin_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_play_break_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_play_ended_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_app_not_installed_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_app_installed_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_app_invoke_failed_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_app_invoke_success_trackers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_area_report_url: Option<String>,
}
