use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct FanglinDevice {
    pub device_type: i32,
    pub os: i32,
    pub os_ver: String,
    pub brand: String,
    pub vendor: String,
    pub model: String,
    pub screen_width: i32,
    pub screen_height: i32,
    pub ua: String,
    pub density: f64,
    pub dpi: i32,
    pub ppi: i32,
    pub imei: String,
    pub oaid: String,
    pub android_id: String,
    pub idfa: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    pub mac: String,
    pub orientation: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub open_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skan_vers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    pub boot_mark: String,
    pub update_mark: String,
    pub device_name_md5: String,
    pub hardware_machine: String,
    pub hardware_model: String,
    pub time_zone: String,
    pub disk_size: String,
    pub memory_size: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    pub os_update_time: String,
    pub boot_time_sec: String,
    pub birth_time: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_com_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapse_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_frequency: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lmt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appstore_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kernel_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms_ver: Option<String>,
}
