use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct FanglinDevice {
    pub device_type: i32,
    pub os: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_width: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_height: Option<i32>,
    pub ua: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ppi: Option<i32>,
    pub imei: String,
    pub oaid: String,
    pub android_id: String,
    pub idfa: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    pub mac: String,
    pub orientation: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub open_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skan_vers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_mark: Option<String>,
    pub device_name_md5: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_machine: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_size: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_update_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_time_sec: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birth_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_com_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapse_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_frequency: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lmt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appstore_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kernel_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms_ver: Option<String>,
}
