use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct UstarsBid {
    pub ad_type: i32,
    pub ad_style: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_urls: Option<Vec<String>>,
    pub url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub win_notice: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub h5_src: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub applet_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub applet_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_package: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_developer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_privacy_policy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_permission: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_size: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_end_card_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_end_card_html: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_prefetch: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_duration: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_size: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_skip: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_orientation: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_skip_min_time: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub show_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_report: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deeplink_fail_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_download_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_download_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_install_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_install_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_start_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_quarter_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_half_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_three_quarters_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_end_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_mute_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_unmute_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_skip_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_close_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_pause_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_resume_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_replay_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_fullscreen_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_exit_fullscreen_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_up_scroll_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_down_scroll_urls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_area_report_url: Option<String>,
}
