use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct UstarsRequest {
    pub req_id: String,
    pub version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imei_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaid_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_id_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openudid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openudid_md5: Option<String>,
    pub app_name: String,
    pub app_package: String,
    pub app_version: String,
    pub ip: String,
    pub user_agent: String,
    pub mac: String,
    pub model: String,
    pub brand: String,
    pub os_type: String,
    pub os_version: String,
    pub device_width: i32,
    pub device_height: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_type: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_duration: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_duration: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i32>,
    pub dpi: i32,
    pub density: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    pub network: String,
    pub connection_type: String,
    pub longitude: f64,
    pub latitude: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_gender: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_age: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_time_zone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_hardware_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_hardware_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_init_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_boot_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_update_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_memory_size: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_disk_size: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_cpu_freq: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_idfa_policy: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_battery_status: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hw_hms: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appstore_version: Option<String>,
    pub boot_mark: String,
    pub update_mark: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_list: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bid_floor: Option<i32>,
}
