use serde::{Deserialize, Serialize};

use super::{AdxworkApp, AdxworkVideo};

#[derive(Serialize, Deserialize)]
pub struct AdxworkAd {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adm: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imgurl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imgs: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub curl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mkurl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dplink: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unlink: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uslink: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imps: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clicks: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adpkg: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub durls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ddurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub surls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sdpurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fdpurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adct: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub admt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<AdxworkVideo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app: Option<AdxworkApp>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_area_report_url: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kswurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kslurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lurls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wxpath: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wxid: Option<String>,
}
