use serde::{Deserialize, Serialize};

use super::AdxworkCaid;

#[derive(Serialize, Deserialize)]
pub struct AdxworkRequest {
    pub id: String,
    #[serde(rename(deserialize = "type", serialize = "type"))]
    pub ad_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adw: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adh: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pkg: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aname: Option<String>,
    pub ua: String,
    pub os: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osl: Option<String>,
    pub mnc: String,
    pub conn: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maker: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub umd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub anid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub omd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caidv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caidvd: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caids: Option<Vec<AdxworkCaid>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oudid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub isdp: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pw: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ph: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub den: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ppi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ori: Option<String>,
    pub dtype: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub isurl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wmac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sysc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub miuiver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hmsver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwagver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appsver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appsvercode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bootmark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updatemark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lat: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lon: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub btime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uptime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dftime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwmodel: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwm: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tzone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub localname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hdisk: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dnmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpunum: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpufreq: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfapolicy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bstatus: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bpower: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub applist: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bidfloor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapsetime: Option<String>,
}
