use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct AdxflowDeviceExt {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_ad_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_store_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms_ver_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_com_time: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_number: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_frequency: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wifi_mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lmt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub installs: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ali_aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birth_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub miui_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rom_ver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skadnetwork_versions: Option<Vec<String>>,
}
