use serde::{Deserialize, Serialize};

use super::{AdwanjiCaid, AdwanjiGeo};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct AdwanjiDevice {
    pub ua: String,
    pub geo: AdwanjiGeo,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    pub devicetype: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub make: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    pub os: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oslevel: Option<i32>,
    pub resolution: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sh: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sw: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ppi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    pub orientation: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfa: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfamd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub udid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imeimd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aidmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oaidmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caidver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caids: Option<Vec<AdwanjiCaid>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub macmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub carrier: Option<String>,
    pub conn: i32,
    pub imsi: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pkgs: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appstorever: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appstorevername: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wifissid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wifimac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serialno: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub countrycode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uiver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub romver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hmsver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwagver: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compilingtime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub starttime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub startnanotime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub startmilltime: Option<String>,
    #[serde(rename(deserialize = "mntId", serialize = "mntId"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mnt_id: Option<String>,
    #[serde(rename(deserialize = "clientTime", serialize = "clientTime"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birthtime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osupdatetime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osupdatenanotime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwmodel: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hwmachine: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sysmemory: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sysdisksize: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpunum: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpufreq: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updatemark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bootmark: Option<String>,
    #[serde(rename(deserialize = "batteryStatus", serialize = "batteryStatus"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<i32>,
    #[serde(rename(deserialize = "batteryPower", serialize = "batteryPower"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(rename(deserialize = "idfaPolicy", serialize = "idfaPolicy"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfa_policy: Option<i32>,
    #[serde(rename(deserialize = "preCaid", serialize = "preCaid"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pre_caid: Option<String>,
    #[serde(rename(deserialize = "preCaidVersion", serialize = "preCaidVersion"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pre_caid_version: Option<String>,
    #[serde(rename(deserialize = "screenSize", serialize = "screenSize"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_size: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reffer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid_vendor: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lastcaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lastcaidver: Option<String>,
}
