use serde::{Deserialize, Serialize};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct AdwanjiEvents {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub els: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clo: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sdls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sils: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eils: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ials: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dclst: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dcls: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dclsf: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_click: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_start: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_first_quartile: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_midpoint: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_third_quartile: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_complete: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_mute: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_unmute: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_skip: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_close: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_suspend: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_full: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_cancelfull: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_cardplay: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_play3s: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_play5s: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_replay: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_upscroll: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_downscroll: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_continue_play: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_load_success: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v_load_fail: Option<Vec<String>>,
}
