use serde::{Deserialize, Serialize};

use super::FwbGeo;

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct FwbDevice {
    pub os: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub osv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub didmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oidmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub androidid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub androididmd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ifa: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ifamd5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub caid_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aaid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openudid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idfv: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub macidmd5: Option<String>,
    pub ip: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    pub ua: String,
    pub connectiontype: i32,
    pub devicetype: i32,
    pub make: String,
    pub model: String,
    pub brand: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub carrier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flashver: Option<String>,
    pub screenheight: i32,
    pub screenwidth: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub orientation: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ppi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<FwbGeo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapsetime: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub romversion: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub syscompilingtime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ag: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wifi_mac: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub udid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birth_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time_msec: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time_nsec: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub local_tz_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_total: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mem_total: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth_status: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skadnetwork_versions: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub miuiversion: Option<String>,
}
