use serde::{Deserialize, Serialize};

use super::{YiweiDeviceId, YiweiGeo};

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct YiweiDevice {
    pub device_id: YiweiDeviceId,
    pub device_type: i32,
    pub ipv4: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    pub ua: String,
    pub os: i32,
    pub osv: String,
    pub manufacturer: String,
    pub brand: String,
    pub model: String,
    pub language: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ro_locale: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale_country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sim_country: Option<String>,
    pub belong_country: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor_country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ro_locale_country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub store_country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub router_country: Option<String>,
    pub orientation: i32,
    pub width: i32,
    pub height: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ppi: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dpr: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sys_ui_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub build_version: Option<String>,
    pub store_version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hms_version: Option<String>,
    pub is_tracking_enabled: bool,
    pub is_gaid_tracking_enabled: bool,
    pub idfa_auth_status: i32,
    pub client_time: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_no: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rom_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_api_level: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_mark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_sec: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_sec: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub up_time: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_freq: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_num: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name_md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_size: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_space_left: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_machine: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hardware_model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_zone_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birth_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compiling_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_power: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub battery_status: Option<i32>,
    pub network: super::YiweiNetwork,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<YiweiGeo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_milli_sec: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_nano_sec: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}
