use serde::{Deserialize, Serialize};

use super::HuichuanVideo;

#[derive(Serialize)]
#[derive(Deserialize)]
pub struct HuichuanAdContent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_aliyun: Option<HuichuanVideo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_duration: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_size: Option<String>,
    pub account_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adm_fixed_ulk: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_logo: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button_content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub close_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub developer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
    pub dsp_bid_price: String,
    pub dsp_logo: String,
    pub dsp_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_desc: Option<String>,
    pub img_1: String,
    pub img_1_h: String,
    pub img_1_w: String,
    pub img_1_t: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_2_h: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_2_w: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_2_t: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_3: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_3_h: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_3_w: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub img_3_t: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market_direct_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mini_app_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mini_app_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheme: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheme_url_ad: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub xiaomi_creative_id: Option<String>,
}
